More distros
OSInside/kiwi-functional-tests pull request #14
Opened 2021-12-03 15:03 UTC by dcermak

Add tests for Archlinux, Ubuntu, Debian, CentOS 7 & 8.

Currently, there's still a lot of failing tests, so this needs further work…

2021-12-17 11:47 UTC, Conan-Kudo requested changes

2021-12-17 11:47 UTC, Conan-Kudo commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
Can we add CentOS 9 too?

2021-12-17 11:50 UTC, dcermak commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
We can, if we had test images in staging.

2021-12-17 13:02 UTC, Conan-Kudo commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
I think @schaefi made those, didn't he?

2021-12-17 13:42 UTC, dcermak commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
It looks like we could actually create these as the repos for CentOS Stream 9 are already there: https://build.opensuse.org/project/show/CentOS:CentOS-9:Stream.
However, this is a bit out of scope of this PR :wink:

2021-12-17 13:49 UTC, dcermak commented
I've made a full test run for Ubuntu, Debian, CentOS and Archlinux and there are now only very few failures left, exclusively on the Archlinux side:
1. see https://github.com/OSInside/kiwi/issues/2005
2. the KIS images for Archlinux cannot be booted by openQA (the capability to do this has simply never been implemented). I would therefore vote to simply omit these until this functionality is added to openQA (if it ever will…)

2021-12-17 15:28 UTC, Conan-Kudo approved these changes

2021-12-17 15:41 UTC, schaefi approved these changes
very nice extending the matrix change :+1:

2022-01-18 07:19 UTC, schaefi commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
The stream9 tests are currently not building, we need to fix the systemdeps requires and there is also a package missing  in stream9 for obs (pv)

2022-01-18 07:20 UTC, schaefi commented
@dcermak This is great work, thanks. I think you should merge it and we will come up with a new PR once stream9 tests builds

2022-01-18 09:44 UTC, dcermak commented
> @dcermak This is great work, thanks. I think you should merge it and we will come up with a new PR once stream9 tests builds

Well, the archlinux tests are still mostly broken atm, so that needs to get fixed before we can proceed here.

2022-01-20 16:04 UTC, schaefi commented on launcher/constants.py
> +CENTOS_8_VERSION = "8"
stream 9 tests are done

2022-01-20 16:05 UTC, schaefi commented
> > @dcermak This is great work, thanks. I think you should merge it and we will come up with a new PR once stream9 tests builds
> 
> Well, the archlinux tests are still mostly broken atm, so that needs to get fixed before we can proceed here.

ok, I think @davidcassany wanted to look at the Arch issues which are related to dracut iirc

2022-01-21 09:45 UTC, Conan-Kudo commented
If Arch Linux is still failing, do we want to disable it until @davidcassany can get things fixed?

2022-06-23 11:10 UTC, schaefi commented
@dcermak with regards to @Conan-Kudo suggestion to disable the Arch tests and your followup commits, can this one be merged now ?

Thanks

2023-01-05 09:18 UTC, schaefi commented
@dcermak This is sitting for a long time. Can you please give an update on the path forward ? Thanks

2023-07-11 12:55 UTC, merged